
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 19 10:10:39 CST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIN_T = 37;
  public static final int Op_relacional = 26;
  public static final int Coma = 36;
  public static final int Llave_c = 33;
  public static final int Op_booleano = 29;
  public static final int Llave_a = 32;
  public static final int Numero_decimal = 41;
  public static final int If = 15;
  public static final int Void = 8;
  public static final int CLASS_T = 7;
  public static final int Else = 16;
  public static final int Corchete_c = 35;
  public static final int Corchete_a = 34;
  public static final int Return = 12;
  public static final int While = 18;
  public static final int Division = 24;
  public static final int Cadena = 14;
  public static final int Parentesis_c = 31;
  public static final int Parentesis_a = 30;
  public static final int For = 19;
  public static final int P_coma = 38;
  public static final int EOF = 0;
  public static final int Printf = 10;
  public static final int error = 1;
  public static final int Libreria = 6;
  public static final int Linea = 2;
  public static final int TIPO_DATO = 13;
  public static final int Op_atribucion = 27;
  public static final int Print = 9;
  public static final int ERROR = 42;
  public static final int Do = 17;
  public static final int Op_logico = 25;
  public static final int Scanf = 11;
  public static final int Identificador = 39;
  public static final int Resta = 22;
  public static final int Multiplicacion = 23;
  public static final int Op_incremento = 28;
  public static final int Numero = 40;
  public static final int Cadena_texto = 4;
  public static final int Suma = 21;
  public static final int Include = 5;
  public static final int Igual = 20;
  public static final int Comillas = 3;
}

